modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mhcore"
version="1.0.0"
displayName="MysticalHardcore Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="test, MCreator"

[[dependencies.mhcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




